from unittest.mock import MagicMock

def load_gemma_model():
    print("MOCK: Loading Gemma Model...")
    model = MagicMock()
    tokenizer = MagicMock()
    
    # Setup mock tokenizer
    tokenizer.eos_token = "<eos>"
    tokenizer.pad_token = "<pad>"
    tokenizer.eos_token_id = 1
    tokenizer.decode.return_value = "This is a mock summary generated by the Reflective Agent."
    
    # Setup mock model generate
    # The inference pipeline expects outputs[0][input_len:]
    # So we need to return a tensor-like object
    
    return model, tokenizer

def setup_lora(model, model_dir):
    print("MOCK: Setting up LoRA...")
    return model
